apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: konga
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: konga
        app: konga
    spec:
      containers:
      - name: konga
        image: pantsel/konga
        # env:
        # - name: DB_ADAPTER
        #   value: postgres
        # - name: DB_HOST
        #   value: mydbendpoint
        #   #valueFrom:
        #   #  secretKeyRef:
        #   #    name: kongcreds
        #   #    key: postgresdbname
        # - name: DB_USER
        #   valueFrom:
        #     secretKeyRef:
        #       name: kongcreds
        #       key: username
        # - name: DB_PASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       name: kongcreds
        #       key: password
        # - name: DB_DATABASE
        #   value: postgres
        # - name: TOKEN_SECRET
        #   value: somesecretstring
        ports:
        - containerPort: 1337
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: konga
  name: konga-svc
spec:
  ports:
    - protocol: TCP
      port: 443
      targetPort: 1337
  selector:
    app: konga
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  name: konga
spec:
  rules:
  - host: kongadmin.mydomain.com
    http:
      paths:
      - backend:
          serviceName: konga-svc
          servicePort: 443
        path: /
  tls:
    - hosts:
      - kongadmin.mydomain.com
      secretName: konga-mydomain-tls